---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-sample
          image: tomcat:8-jre8-alpine
          ports:
            - containerPort: 8080
          env:
            - name: STATIC_VAR
              value: "Hello from environment"
