---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat-sample
      image: harbor.prodyna.com/training/tomcat-sample:azure-training-5
      ports:
        - containerPort: 8080
      env:
        - name: STATIC_VAR
          value: "Hello from environment"
